### ISSUE TITLE
HTTP 500 Error Encountered Sorry. Please, contact me if this error repeats

### ISSUE THREAD

**Issue by dimka11** [vol1ura/strava_weather_app#5]
I get following error after strava authorization, on http://127.0.0.1:5000/authorization_successful?state=&code=CODEHERE&scope=read,activity:write,activity:read_all What should I do?
Also I don't know where I can get SECRET_KEY and STRAVA_WEBHOOK_TOKEN

In console:

```
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [02/Jun/2022 17:39:09] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2022 17:39:09] "GET /static/cover.css HTTP/1.1" 304 -
127.0.0.1 - - [02/Jun/2022 17:39:09] "GET /static/logo-strava.png HTTP/1.1" 304 -
127.0.0.1 - - [02/Jun/2022 17:39:09] "GET /static/logo-strava-echelon.png HTTP/1.1" 304 -
127.0.0.1 - - [02/Jun/2022 17:39:10] "GET /static/favicon-16x16.png HTTP/1.1" 304 -
[2022-06-02 17:39:15,338] ERROR in app: Exception on /authorization_successful [GET]
Traceback (most recent call last):
  File "C:\Users\Dima\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Dima\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Dima\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Dima\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "run.py", line 55, in auth
    manage_db.add_athlete(tokens)
  File "B:\strava_weather_app\utils\manage_db.py", line 29, in add_athlete
    tokens_db = get_athlete(tokens.id)
  File "B:\strava_weather_app\utils\manage_db.py", line 21, in get_athlete
    db = get_db()
  File "B:\strava_weather_app\utils\manage_db.py", line 15, in get_db
    g.db = sqlite3.connect(current_app.config['DATABASE'], detect_types=sqlite3.PARSE_DECLTYPES)
sqlite3.OperationalError: unable to open database file
```

**Comment by dimka11** [comment]
Ok, I did solve problem with database, but there is still 500 error without errors in console

**Comment by vol1ura** [comment]
Hi,
`SECRET_KEY` - any secret string for configuring your Flask application. You can set it directly in `run.py:16`. 
`STRAVA_WEBHOOK_TOKEN` - any secret string that you send to Strava in subscription request. See details in official manual https://developers.strava.com/docs/webhooks/ in section "Create a subscription". You should subscribe to webhooks before running this app.
